# Generated by Django 4.2.5 on 2023-09-28 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="meal",
            name="calories",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="carbohydrateContent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="cholesterolContent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="fatContent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="fiberContent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="image",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meal",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="proteinContent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="saturatedFatContent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="sodiumContent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="sugarContent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="ingredients",
            field=models.ManyToManyField(to="meals.ingredient"),
        ),
        migrations.AddField(
            model_name="meal",
            name="keywords",
            field=models.ManyToManyField(to="meals.keyword"),
        ),
    ]
