# Generated by Django 4.2.5 on 2023-09-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0002_ingredient_keyword_meal_calories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="ingredients", to="meals.ingredient"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="keywords",
            field=models.ManyToManyField(related_name="keywords", to="meals.keyword"),
        ),
        migrations.AlterField(
            model_name="meal",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
