# Generated by Django 4.2.5 on 2023-09-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calories", models.FloatField(default=0)),
                ("carbohydrateContent", models.FloatField(default=0)),
                ("cholesterolContent", models.FloatField(default=0)),
                ("fatContent", models.FloatField(default=0)),
                ("fiberContent", models.FloatField(default=0)),
                ("proteinContent", models.FloatField(default=0)),
                ("saturatedFatContent", models.FloatField(default=0)),
                ("sodiumContent", models.FloatField(default=0)),
                ("sugarContent", models.FloatField(default=0)),
                ("condition_name", models.CharField(default=0, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
