# Generated by Django 4.2.5 on 2023-10-28 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calories", models.FloatField(default=0)),
                ("carbohydrateContent", models.FloatField(default=0)),
                ("cholesterolContent", models.FloatField(default=0)),
                ("fatContent", models.FloatField(default=0)),
                ("fiberContent", models.FloatField(default=0)),
                ("proteinContent", models.FloatField(default=0)),
                ("saturatedFatContent", models.FloatField(default=0)),
                ("sodiumContent", models.FloatField(default=0)),
                ("sugarContent", models.FloatField(default=0)),
                ("condition_name", models.CharField(default=0, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
